/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SfwPageTitle.java
 *
 * Created on 13/11/2008, 15:32:25
 */

package sfwinstaladorscript.components;

/**
 * Componente título de uma página wizard.
 */
public class SfwWizardPageTitle extends javax.swing.JPanel {

    /** Creates new form SfwPageTitle */
    public SfwWizardPageTitle() {
        initComponents();
    }

    public String getSubtitulo() {
        return jLabelSubTitle.getText();
    }

    public void setSubtitulo(String subtitulo) {
        this.jLabelSubTitle.setText(subtitulo);
    }

    public String getTitulo() {
        return jLabelTitle.getText();
    }

    public void setTitulo(String titulo) {
        this.jLabelTitle.setText(titulo);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubTitle = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(579, 25));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardPageTitle.class);
        jLabelSubTitle.setFont(resourceMap.getFont("jLabelSubTitle.font")); // NOI18N
        jLabelSubTitle.setForeground(resourceMap.getColor("jLabelSubTitle.foreground")); // NOI18N
        jLabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubTitle.setText(resourceMap.getString("jLabelSubTitle.text")); // NOI18N
        jLabelSubTitle.setName("jLabelSubTitle"); // NOI18N

        jLabelTitle.setFont(resourceMap.getFont("jLabelTitle.font")); // NOI18N
        jLabelTitle.setForeground(resourceMap.getColor("jLabelTitle.foreground")); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText(resourceMap.getString("jLabelTitle.text")); // NOI18N
        jLabelTitle.setName("jLabelTitle"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(151, 151, 151)
                .add(jLabelTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 259, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelSubTitle)
                .add(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabelTitle)
                .add(jLabelSubTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables

}
