/*
 * SfwInstaladorScriptAboutBox.java
 */

package sfwinstaladorscript;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import org.jdesktop.application.Action;

/**
 * Representa tela com informações do sistema.
 */
public class SfwInstaladorScriptSystemInfo extends javax.swing.JDialog {

    public SfwInstaladorScriptSystemInfo(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        this.jTextFieldOS.setText(System.getProperty("os.name"));
        this.jTextFieldOSVer.setText(System.getProperty("os.version"));
        this.jTextFieldOSArch.setText(System.getProperty("os.arch"));
        this.jTextFieldJavaHome.setText(System.getProperty("java.home"));
        this.jTextFieldJavaVersion.setText(System.getProperty("java.version"));
        this.jTextFieldJavaVM.setText(System.getProperty("java.vm.name"));
        this.jTextFieldJavaVMVer.setText(System.getProperty("java.vm.version"));

        try {
            Process p = Runtime.getRuntime().exec("sqlplus -V");
            p.waitFor();
            InputStream inr = p.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(inr));

            String s = br.readLine();
            if(s.equals(""))
               s = br.readLine();

            if(!s.equals(""))
                this.jTextFieldDbOracle.setText(s);

        } catch (InterruptedException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    @Action 
    /**
     * Ação de fechar tela de informações do sistema.
     */
    public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldOSArch = new javax.swing.JTextField();
        jTextFieldOSVer = new javax.swing.JTextField();
        jTextFieldOS = new javax.swing.JTextField();
        jLabelOS = new javax.swing.JLabel();
        jLabelOSVer = new javax.swing.JLabel();
        jLabelOSArch = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldJavaHome = new javax.swing.JTextField();
        jLabelJavaHome = new javax.swing.JLabel();
        jTextFieldJavaVersion = new javax.swing.JTextField();
        jLabelJavaVersion = new javax.swing.JLabel();
        jTextFieldJavaVM = new javax.swing.JTextField();
        jLabelJavaVM = new javax.swing.JLabel();
        jTextFieldJavaVMVer = new javax.swing.JTextField();
        jLabelJavaVMVer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelDbOracle = new javax.swing.JLabel();
        jTextFieldDbOracle = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwInstaladorScriptSystemInfo.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("systemInfo"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setFont(resourceMap.getFont("jPanel1.font")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jTextFieldOSArch.setEditable(false);
        jTextFieldOSArch.setName("jTextFieldOSArch"); // NOI18N

        jTextFieldOSVer.setEditable(false);
        jTextFieldOSVer.setName("jTextFieldOSVer"); // NOI18N

        jTextFieldOS.setEditable(false);
        jTextFieldOS.setText(resourceMap.getString("jTextFieldOS.text")); // NOI18N
        jTextFieldOS.setName("jTextFieldOS"); // NOI18N

        jLabelOS.setText(resourceMap.getString("jLabelOS.text")); // NOI18N
        jLabelOS.setName("jLabelOS"); // NOI18N

        jLabelOSVer.setText(resourceMap.getString("jLabelOSVer.text")); // NOI18N
        jLabelOSVer.setName("jLabelOSVer"); // NOI18N

        jLabelOSArch.setText(resourceMap.getString("jLabelOSArch.text")); // NOI18N
        jLabelOSArch.setName("jLabelOSArch"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelOS)
                    .add(jLabelOSVer)
                    .add(jLabelOSArch))
                .add(38, 38, 38)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldOSArch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .add(jTextFieldOSVer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .add(jTextFieldOS, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelOS)
                    .add(jTextFieldOS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelOSVer)
                    .add(jTextFieldOSVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelOSArch)
                    .add(jTextFieldOSArch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jTextFieldJavaHome.setEditable(false);
        jTextFieldJavaHome.setName("jTextFieldJavaHome"); // NOI18N

        jLabelJavaHome.setText(resourceMap.getString("jLabelJavaHome.text")); // NOI18N
        jLabelJavaHome.setName("jLabelJavaHome"); // NOI18N

        jTextFieldJavaVersion.setEditable(false);
        jTextFieldJavaVersion.setName("jTextFieldJavaVersion"); // NOI18N

        jLabelJavaVersion.setText(resourceMap.getString("jLabelJavaVersion.text")); // NOI18N
        jLabelJavaVersion.setName("jLabelJavaVersion"); // NOI18N

        jTextFieldJavaVM.setEditable(false);
        jTextFieldJavaVM.setName("jTextFieldJavaVM"); // NOI18N

        jLabelJavaVM.setText(resourceMap.getString("jLabelJavaVM.text")); // NOI18N
        jLabelJavaVM.setName("jLabelJavaVM"); // NOI18N

        jTextFieldJavaVMVer.setEditable(false);
        jTextFieldJavaVMVer.setName("jTextFieldJavaVMVer"); // NOI18N

        jLabelJavaVMVer.setText(resourceMap.getString("jLabelJavaVMVer.text")); // NOI18N
        jLabelJavaVMVer.setName("jLabelJavaVMVer"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelJavaVM)
                    .add(jLabelJavaVersion)
                    .add(jLabelJavaHome)
                    .add(jLabelJavaVMVer))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldJavaVM)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldJavaVersion)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldJavaVMVer)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldJavaHome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 347, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelJavaHome)
                    .add(jTextFieldJavaHome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelJavaVersion)
                    .add(jTextFieldJavaVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelJavaVM)
                    .add(jTextFieldJavaVM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelJavaVMVer)
                    .add(jTextFieldJavaVMVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel3.border.titleFont"), resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jLabelDbOracle.setText(resourceMap.getString("jLabelDbOracle.text")); // NOI18N
        jLabelDbOracle.setName("jLabelDbOracle"); // NOI18N

        jTextFieldDbOracle.setEditable(false);
        jTextFieldDbOracle.setName("jTextFieldDbOracle"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelDbOracle)
                .add(18, 18, 18)
                .add(jTextFieldDbOracle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelDbOracle)
                    .add(jTextFieldDbOracle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getActionMap(SfwInstaladorScriptSystemInfo.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(405, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabelDbOracle;
    private javax.swing.JLabel jLabelJavaHome;
    private javax.swing.JLabel jLabelJavaVM;
    private javax.swing.JLabel jLabelJavaVMVer;
    private javax.swing.JLabel jLabelJavaVersion;
    private javax.swing.JLabel jLabelOS;
    private javax.swing.JLabel jLabelOSArch;
    private javax.swing.JLabel jLabelOSVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldDbOracle;
    private javax.swing.JTextField jTextFieldJavaHome;
    private javax.swing.JTextField jTextFieldJavaVM;
    private javax.swing.JTextField jTextFieldJavaVMVer;
    private javax.swing.JTextField jTextFieldJavaVersion;
    private javax.swing.JTextField jTextFieldOS;
    private javax.swing.JTextField jTextFieldOSArch;
    private javax.swing.JTextField jTextFieldOSVer;
    // End of variables declaration//GEN-END:variables
    
}
