/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SfwWizardValidator.java
 *
 * Created on 30/10/2008, 17:22:31
 */
package sfwinstaladorscript.oracleinstallation;

import java.awt.event.KeyEvent;
import sfwinstaladorscript.*;
import java.awt.Color;
import java.awt.event.KeyListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskMonitor;
import sfwinstaladorscript.database.OracleConnection;
import sfwinstaladorscript.database.OracleValidationResult;
import sfwinstaladorscript.interfaces.SfwWizardPage;
import sfwinstaladorscript.Utils;
import sfwinstaladorscript.oracleinstallation.components.SfwOracleDefineUser;

/**
 * Página de validações de base de dados.
 */
public class SfwWizardOracleValidator extends javax.swing.JPanel implements SfwWizardPage {

    private OracleConnection _oraconn;
    private SfwInstaladorScriptView _view;
    private Task _validatebase;

    /** Creates new form SfwWizardValidator */
    public SfwWizardOracleValidator(SfwInstaladorScriptView view) {

        initComponents();

        this._view = view;
        this._oraconn = new OracleConnection();
        this.jTextFieldTNS.setToolTipText(Utils.getDefaultBundle().getString("Database.msghint"));

        this.jTextFieldTNS.requestFocus();

        this.jTextFieldTNS.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                jButtonValidate.setEnabled(true);
                _view.getNextButton().setEnabled(false);
                resetValidation();
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });

        this.jTextFieldTNS.setText(Install.get_tns());
        
        /*if (Profile.isSet()) {
            this.jTextFieldTNS.setText(Install);
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldVersion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldJava = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldParameters = new javax.swing.JTextField();
        jButtonValidate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPermission = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRole = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldTNS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSombra = new javax.swing.JTextField();
        sfwPageTitle = new sfwinstaladorscript.components.SfwWizardPageTitle();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardOracleValidator.class);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jTextFieldVersion.setEditable(false);
        jTextFieldVersion.setForeground(resourceMap.getColor("jTextFieldVersion.foreground")); // NOI18N
        jTextFieldVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVersion.setText(resourceMap.getString("jTextFieldVersion.text")); // NOI18N
        jTextFieldVersion.setName("jTextFieldVersion"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldJava.setEditable(false);
        jTextFieldJava.setForeground(resourceMap.getColor("jTextFieldJava.foreground")); // NOI18N
        jTextFieldJava.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJava.setText(resourceMap.getString("jTextFieldJava.text")); // NOI18N
        jTextFieldJava.setName("jTextFieldJava"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextFieldParameters.setEditable(false);
        jTextFieldParameters.setForeground(resourceMap.getColor("jTextFieldParameters.foreground")); // NOI18N
        jTextFieldParameters.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldParameters.setText(resourceMap.getString("jTextFieldParameters.text")); // NOI18N
        jTextFieldParameters.setName("jTextFieldParameters"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getActionMap(SfwWizardOracleValidator.class, this);
        jButtonValidate.setAction(actionMap.get("validateClick")); // NOI18N
        jButtonValidate.setText(resourceMap.getString("jButtonValidate.text")); // NOI18N
        jButtonValidate.setName("jButtonValidate"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setBackground(resourceMap.getColor("jTextAreaLog.background")); // NOI18N
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setFont(resourceMap.getFont("jTextAreaLog.font")); // NOI18N
        jTextAreaLog.setLineWrap(true);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setName("jTextAreaLog"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaLog);

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jTextFieldPermission.setEditable(false);
        jTextFieldPermission.setForeground(resourceMap.getColor("jTextFieldPermission.foreground")); // NOI18N
        jTextFieldPermission.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPermission.setText(resourceMap.getString("jTextFieldPermission.text")); // NOI18N
        jTextFieldPermission.setName("jTextFieldPermission"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jTextFieldRole.setEditable(false);
        jTextFieldRole.setForeground(resourceMap.getColor("jTextFieldRole.foreground")); // NOI18N
        jTextFieldRole.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRole.setText(resourceMap.getString("jTextFieldRole.text")); // NOI18N
        jTextFieldRole.setName("jTextFieldRole"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(217, 65));

        jTextFieldTNS.setText(resourceMap.getString("jTextFieldTNS.text")); // NOI18N
        jTextFieldTNS.setEnabled(false);
        jTextFieldTNS.setName("jTextFieldTNS"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldTNS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldTNS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jTextFieldSombra.setEditable(false);
        jTextFieldSombra.setForeground(resourceMap.getColor("jTextFieldSombra.foreground")); // NOI18N
        jTextFieldSombra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSombra.setText(resourceMap.getString("jTextFieldSombra.text")); // NOI18N
        jTextFieldSombra.setName("jTextFieldSombra"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(57, 57, 57)
                        .add(jButtonValidate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel7)
                            .add(jLabel9)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldJava, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldParameters, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldPermission, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldRole, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jLabel2, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.linkSize(new java.awt.Component[] {jTextFieldJava, jTextFieldParameters, jTextFieldPermission, jTextFieldRole, jTextFieldSombra, jTextFieldVersion}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jTextFieldVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jTextFieldJava, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jTextFieldParameters, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jTextFieldPermission, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(12, 12, 12)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldRole, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jButtonValidate))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sfwPageTitle.setName("sfwPageTitle"); // NOI18N
        sfwPageTitle.setSubtitulo(resourceMap.getString("sfwPageTitle.subtitulo")); // NOI18N
        sfwPageTitle.setTitulo(resourceMap.getString("sfwPageTitle.titulo")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(sfwPageTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(sfwPageTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Implementação de setup inicial da página.
     * @param view Frame principal da aplicação.
     */
    public void flowSetup(SfwInstaladorScriptView view) {
        view.getBackButton().setEnabled(true);
        view.getNextButton().setEnabled(false);
    }

    public void nextClick(Hashtable wzPages, SfwInstaladorScriptView view) {
        Install.set_tns(this.jTextFieldTNS.getText());
        view.setWizardPage((JPanel) wzPages.get("wzValidator2"));
    }

    public void backClick(Hashtable wzPages, SfwInstaladorScriptView view) {

        if (this._validatebase != null && (this._validatebase.isPending() || this._validatebase.isStarted())) {
            this._validatebase.cancel(false);
            Utils.setDefaultCursor();
            _view.getBusyIconTimer().stop();
            _view.getStatusAnimationLabel().setIcon(_view.getIdleIcon());
            _view.getStatusAnimationLabel().setText("");
        }

        this.resetValidation();
        this.jButtonValidate.setEnabled(true);
        
        view.setWizardPage((JPanel) wzPages.get("wzInstalledProduct"));
        view.getNextButton().setEnabled(true);
    }

    /**
     * Limpa campos de validação.
     */
    private void resetValidation() {
        this.jTextAreaLog.setText("");
        this.jTextFieldVersion.setText(Utils.getDefaultBundle(this).getString("jTextFieldVersion.text"));
        this.jTextFieldVersion.setForeground(new Color(255, 0, 0));
        this.jTextFieldJava.setText(Utils.getDefaultBundle(this).getString("jTextFieldJava.text"));
        this.jTextFieldJava.setForeground(new Color(255, 0, 0));
        this.jTextFieldParameters.setText(Utils.getDefaultBundle(this).getString("jTextFieldParameters.text"));
        this.jTextFieldParameters.setForeground(new Color(255, 0, 0));
        this.jTextFieldPermission.setText(Utils.getDefaultBundle(this).getString("jTextFieldPermission.text"));
        this.jTextFieldPermission.setForeground(new Color(255, 0, 0));
        this.jTextFieldSombra.setText(Utils.getDefaultBundle(this).getString("jTextFieldSombra.text"));
        this.jTextFieldSombra.setForeground(new Color(255, 0, 0));
        this.jTextFieldRole.setText(Utils.getDefaultBundle(this).getString("jTextFieldRole.text"));
        this.jTextFieldRole.setForeground(new Color(255, 0, 0));
    }

    @Action
    public void validateClick() {

        TaskMonitor taskMonitor = new TaskMonitor(this._view.getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    _view.getBusyIconTimer().start();
                    _view.getStatusAnimationLabel().setText(Utils.getDefaultBundle().getString("Validation.statusconnecting"));
                } else if ("done".equals(propertyName)) {
                    _view.getBusyIconTimer().stop();
                    _view.getStatusAnimationLabel().setIcon(_view.getIdleIcon());
                    _view.getStatusAnimationLabel().setText("");
                } else if ("message".equals(propertyName)) {
                } else if ("progress".equals(propertyName)) {
                }
            }
        });


        this._validatebase = new Task(this._view.getApplication()) {

            @Override
            protected Object doInBackground() throws Exception {

                Iterator v_iterator_it;
                String v_string_vpermission = "";
                SfwOracleProductDetail v_sfworacleproductdetail_pd;
                SfwOracleDefineUser v_sfworacleproductdetail_du;
                OracleValidationResult v_oraclevalidationresult_vversion, v_oraclevalidationresult_vjava, v_oraclevalidationresult_vparameter, v_oraclevalidationresult_result_permissionsombra;
                OracleValidationResult v_oraclevalidationresult_result_permission;

                Utils.setBusyCursor();

                if (jTextFieldTNS.getText().equals("")) {
                    Utils.setDefaultCursor();
                    JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("validationtns"), java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("validationlabel"), JOptionPane.WARNING_MESSAGE);
                    jTextFieldTNS.requestFocus();
                    jButtonValidate.setEnabled(true);
                    return null;
                }

                _oraconn.set_tns(jTextFieldTNS.getText());
                jTextAreaLog.setText("");

                _oraconn.set_username(((SfwOracleProductDetail) Install.get_productsdetail().get(0)).getUser());
                _oraconn.set_password(((SfwOracleProductDetail) Install.get_productsdetail().get(0)).getPassword());
                jTextAreaLog.setText(java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgconnectingto") + " " + ((SfwOracleProductDetail) Install.get_productsdetail().get(0)).getUser() + "/******..." + System.getProperty("line.separator") + System.getProperty("line.separator"));

                try {
                    try {
                        _oraconn.Connect();
                    } catch (SQLException e) {
                        if (e.getErrorCode() == 1017) {
                            Utils.setDefaultCursor();
                            _oraconn.Close();
                            e.printStackTrace();
                            jTextAreaLog.setText(jTextAreaLog.getText() + "" + String.format(java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgcreatesession"), _oraconn.get_username(), System.getProperty("line.separator")));
                            jButtonValidate.setEnabled(true);
                            return null;
                        }
                        if (e.getErrorCode() == 0) {
                            Utils.setDefaultCursor();
                            _oraconn.Close();
                            e.printStackTrace();
                            jTextAreaLog.setText(jTextAreaLog.getText() + "" + String.format(java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgtnserror")));
                            jButtonValidate.setEnabled(true);
                            return null;
                        }
                        if (e.getErrorCode() == 17002) {
                            Utils.setDefaultCursor();
                            _oraconn.Close();
                            e.printStackTrace();
                            jTextAreaLog.setText(jTextAreaLog.getText() + "" + String.format(java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgtnserror")));
                            jButtonValidate.setEnabled(true);
                            return null;
                        }
                    } catch (Exception e) {
                        Utils.setDefaultCursor();
                        _oraconn.Close();
                        e.printStackTrace();
                        jTextAreaLog.setText(jTextAreaLog.getText() + "" + String.format(java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgcreatesession"), _oraconn.get_username(), System.getProperty("line.separator")));
                        jButtonValidate.setEnabled(true);
                        return null;
                    }

                    //valida versão do banco
                    v_oraclevalidationresult_vversion = _oraconn.ValidateVersion();
                    jTextFieldVersion.setText(v_oraclevalidationresult_vversion.get_result_text());
                    jTextFieldVersion.setForeground(v_oraclevalidationresult_vversion.get_result_color());

                    if (!v_oraclevalidationresult_vversion.get_text().equals("")) {
                        jTextAreaLog.setText(jTextAreaLog.getText() + "ORACLE:" + System.getProperty("line.separator") + "--------------------------------------------" + System.getProperty("line.separator"));
                        jTextAreaLog.setText(jTextAreaLog.getText() + v_oraclevalidationresult_vversion.get_text() + System.getProperty("line.separator") + System.getProperty("line.separator"));
                    }

                    //valida java
                    v_oraclevalidationresult_vjava = _oraconn.ValidateJava();
                    jTextFieldJava.setText(v_oraclevalidationresult_vjava.get_result_text());
                    jTextFieldJava.setForeground(v_oraclevalidationresult_vjava.get_result_color());

                    if (!v_oraclevalidationresult_vjava.get_text().equals("")) {
                        jTextAreaLog.setText(jTextAreaLog.getText() + "JAVA:" + System.getProperty("line.separator") + "--------------------------------------------" + System.getProperty("line.separator"));
                        jTextAreaLog.setText(jTextAreaLog.getText() + v_oraclevalidationresult_vjava.get_text() + System.getProperty("line.separator"));
                    }

                    //valida parametros banco
                    v_oraclevalidationresult_vparameter = _oraconn.ValidateParameters();
                    jTextFieldParameters.setText(v_oraclevalidationresult_vparameter.get_result_text());
                    jTextFieldParameters.setForeground(v_oraclevalidationresult_vparameter.get_result_color());

                    if (!v_oraclevalidationresult_vparameter.get_text().equals("")) {
                        jTextAreaLog.setText(jTextAreaLog.getText() + java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgparameters") + ":" + System.getProperty("line.separator") + "--------------------------------------------" + System.getProperty("line.separator"));
                        jTextAreaLog.setText(jTextAreaLog.getText() + v_oraclevalidationresult_vparameter.get_text() + System.getProperty("line.separator"));
                    }

                    //valida permissoes dos produtos
                    v_iterator_it = Install.get_productsdetail().iterator();
                    v_oraclevalidationresult_result_permission = null;
                    v_oraclevalidationresult_result_permissionsombra = null;

                    while (v_iterator_it.hasNext()) {
                        v_sfworacleproductdetail_pd = (SfwOracleProductDetail) v_iterator_it.next();
                        v_oraclevalidationresult_vjava = _oraconn.ValidatePermission(v_sfworacleproductdetail_pd);

                        if (v_oraclevalidationresult_result_permission != null) {
                            if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.ERROR)) {
                                v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                            } else if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.WARN) && v_oraclevalidationresult_result_permission.get_result().equals(OracleValidationResult.Result.SUCCESS)) {
                                v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                            }
                        } else {
                            v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                        }

                        v_string_vpermission = v_string_vpermission + v_oraclevalidationresult_vjava.get_text();
                    }

                    v_iterator_it = Install.get_productdefine().iterator();

                    while (v_iterator_it.hasNext()) {
                        v_sfworacleproductdetail_du = (SfwOracleDefineUser) v_iterator_it.next();
                        v_oraclevalidationresult_vjava = _oraconn.ValidatePermission(v_sfworacleproductdetail_du);

                        if (v_oraclevalidationresult_result_permission != null) {
                            if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.ERROR)) {
                                v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                            } else if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.WARN) && v_oraclevalidationresult_result_permission.get_result().equals(OracleValidationResult.Result.SUCCESS)) {
                                v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                            }
                        } else {
                            v_oraclevalidationresult_result_permission = v_oraclevalidationresult_vjava;
                        }

                        v_string_vpermission = v_string_vpermission + v_oraclevalidationresult_vjava.get_text();
                    }

                    jTextFieldPermission.setText(v_oraclevalidationresult_result_permission.get_result_text());
                    jTextFieldPermission.setForeground(v_oraclevalidationresult_result_permission.get_result_color());

                    //valida permissoes do Sombra
                    v_oraclevalidationresult_vjava = _oraconn.ValidatePermissionSombra(Profile.getUsuariosombra(), Profile.getSenhasombra());

                    if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.ERROR)) {
                        v_oraclevalidationresult_result_permissionsombra = v_oraclevalidationresult_vjava;
                    } else if (v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.WARN) && v_oraclevalidationresult_result_permissionsombra.get_result().equals(OracleValidationResult.Result.SUCCESS)) {
                        v_oraclevalidationresult_result_permissionsombra = v_oraclevalidationresult_vjava;
                    }

                    v_oraclevalidationresult_result_permissionsombra = v_oraclevalidationresult_vjava;

                    v_string_vpermission = v_string_vpermission + v_oraclevalidationresult_vjava.get_text();

                    jTextFieldSombra.setText(v_oraclevalidationresult_result_permissionsombra.get_result_text());
                    jTextFieldSombra.setForeground(v_oraclevalidationresult_result_permissionsombra.get_result_color());

                    // Valida se a role digitada � v�lida
                    if (!v_oraclevalidationresult_result_permissionsombra.get_result().equals(OracleValidationResult.Result.ERROR)) {
                        OracleConnection v_conn = new OracleConnection();
                        SfwOracleProductDetail v_sfworacleproduct = null;
                        try {
                            v_iterator_it = Install.get_productsdetail().iterator();
                            while (v_iterator_it.hasNext()) {
                                v_sfworacleproduct = (SfwOracleProductDetail) v_iterator_it.next();
                                v_conn.set_username(Profile.getUsuariosombra());
                                v_conn.set_password(Profile.getSenhasombra());
                                v_conn.set_tns(jTextFieldTNS.getText());
                                break;
                            }
                            v_conn.ConnectAux();
                        } catch (Exception e) {
                        }

                        v_oraclevalidationresult_result_permissionsombra = v_conn.ValidateRole(v_sfworacleproduct, jTextFieldTNS.getText());

                        v_string_vpermission = v_string_vpermission + v_oraclevalidationresult_result_permissionsombra.get_text();

                        jTextFieldRole.setText(v_oraclevalidationresult_result_permissionsombra.get_result_text());
                        jTextFieldRole.setForeground(v_oraclevalidationresult_result_permissionsombra.get_result_color());
                    }


                    if (!v_string_vpermission.equals("")) {
                        jTextAreaLog.setText(jTextAreaLog.getText() + java.util.ResourceBundle.getBundle("sfwinstaladorscript/oracleinstallation/resources/SfwWizardOracleValidator").getString("msgpermission") + ":" + System.getProperty("line.separator") + "--------------------------------------------" + System.getProperty("line.separator"));
                        jTextAreaLog.setText(jTextAreaLog.getText() + v_string_vpermission);
                    }

                    _oraconn.Close();

                    jButtonValidate.setEnabled(true);
                    Utils.setDefaultCursor();

                    if (!v_oraclevalidationresult_vversion.get_result().equals(OracleValidationResult.Result.ERROR)
                            && !v_oraclevalidationresult_vjava.get_result().equals(OracleValidationResult.Result.ERROR)
                            && !v_oraclevalidationresult_vparameter.get_result().equals(OracleValidationResult.Result.ERROR)
                            && !v_oraclevalidationresult_result_permission.get_result().equals(OracleValidationResult.Result.ERROR)
                            && !v_oraclevalidationresult_result_permissionsombra.get_result().equals(OracleValidationResult.Result.ERROR)) {
                        try {
                            WriteValidations();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        _view.getNextButton().setEnabled(true);
                    } else {
                        _view.getNextButton().setEnabled(false);
                    }

                    return null;

                } catch (SQLException ex) {
                    Utils.setDefaultCursor();
                    _oraconn.Close();
                    ex.printStackTrace();
                    jTextAreaLog.setText(jTextAreaLog.getText() + System.getProperty("line.separator") + ex.getMessage());
                    jButtonValidate.setEnabled(true);
                    return null;
                }
            }
        };

        taskMonitor.setForegroundTask(
                this._validatebase);
        jButtonValidate.setEnabled(
                false);
        jTextFieldTNS.setEnabled(
                false);

        this.resetValidation();

        this._validatebase.execute();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldJava;
    private javax.swing.JTextField jTextFieldParameters;
    private javax.swing.JTextField jTextFieldPermission;
    private javax.swing.JTextField jTextFieldRole;
    private javax.swing.JTextField jTextFieldSombra;
    private javax.swing.JTextField jTextFieldTNS;
    private javax.swing.JTextField jTextFieldVersion;
    private sfwinstaladorscript.components.SfwWizardPageTitle sfwPageTitle;
    // End of variables declaration//GEN-END:variables

    private void WriteValidations() throws Exception {
        if (!new File("log").exists()) {
            new File("log").mkdirs();
        }
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(new File("log\\parameter_" + jTextFieldTNS.getText() + "_" + new SimpleDateFormat("yyyyMMdd").format(new Date()) + ".txt")), "ISO-8859-1"));
        bw.write(jTextAreaLog.getText());
        bw.flush();
        bw.close();
    }
}
