package sfwinstaladorscript.oracleinstallation;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskMonitor;

import sfwinstaladorscript.Install;
import sfwinstaladorscript.Mail;
import sfwinstaladorscript.Profile;
import sfwinstaladorscript.SfwInstaladorScriptView;
import sfwinstaladorscript.SfwWizardSetup;
import sfwinstaladorscript.Utils;
import sfwinstaladorscript.database.OracleConnection;
import sfwinstaladorscript.interfaces.SfwWizardPage;
import sfwinstaladorscript.objects.PackageFinal;
import sfwinstaladorscript.objects.Product;
import sfwinstaladorscript.oracleinstallation.components.SfwOracleDefineUser;
import sfwinstaladorscript.oracleinstallation.components.SfwOraclePackageInstall;

/**
 * Tela para instala√ß√£o dos produtos.
 */
public class SfwWizardOracleInstall extends javax.swing.JPanel implements SfwWizardPage {

    private int _currentindex;
    private ArrayList _productpkg;
    private SfwInstaladorScriptView _view;
    private Task _installpackagetask;
    private boolean _finalexecuted;

    /** Creates new form SfwWizardOracleInstall */
    public SfwWizardOracleInstall(SfwInstaladorScriptView view) {

        initComponents();

        this._view = view;
        this._currentindex = -1;
        this._finalexecuted = false;

        this.sfwListProducts.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (sfwListProducts.isEnabled()) {
                    jScrollPanePackages.setViewportView((JPanel) _productpkg.get(sfwListProducts.getSelectedIndex()));
                }
            }
        });
    }

    /**
     * Retorna bot√£o de instala√ß√£o de tudo.
     * @return Componente bot√£o instala√ß√£o de tudo.
     */
    public JButton getJButtonInstallAll() {
        return jButtonInstallAll;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfwWizardPageTitle1 = new sfwinstaladorscript.components.SfwWizardPageTitle();
        jScrollPanePackages = new javax.swing.JScrollPane();
        jPanelProducts = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sfwListProducts = new sfwinstaladorscript.components.SfwList();
        jButtonInstallAll = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(599, 372));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        sfwWizardPageTitle1.setName("sfwWizardPageTitle1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardOracleInstall.class);
        sfwWizardPageTitle1.setSubtitulo(resourceMap.getString("sfwWizardPageTitle1.subtitulo")); // NOI18N
        sfwWizardPageTitle1.setTitulo(resourceMap.getString("sfwWizardPageTitle1.titulo")); // NOI18N

        jScrollPanePackages.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jScrollPanePackages.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jScrollPanePackages.border.titleFont"), resourceMap.getColor("jScrollPanePackages.border.titleColor"))); // NOI18N
        jScrollPanePackages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePackages.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPanePackages.setName("jScrollPanePackages"); // NOI18N

        jPanelProducts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelProducts.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanelProducts.border.titleFont"), resourceMap.getColor("jPanelProducts.border.titleColor"))); // NOI18N
        jPanelProducts.setName("jPanelProducts"); // NOI18N
        jPanelProducts.setPreferredSize(new java.awt.Dimension(136, 291));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        sfwListProducts.setBackground(resourceMap.getColor("sfwListProducts.background")); // NOI18N
        sfwListProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sfwListProducts.setEnabled(false);
        sfwListProducts.setFixedCellHeight(20);
        sfwListProducts.setName("sfwListProducts"); // NOI18N
        jScrollPane3.setViewportView(sfwListProducts);

        org.jdesktop.layout.GroupLayout jPanelProductsLayout = new org.jdesktop.layout.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getActionMap(SfwWizardOracleInstall.class, this);
        jButtonInstallAll.setAction(actionMap.get("installAllClick")); // NOI18N
        jButtonInstallAll.setText(resourceMap.getString("jButtonInstallAll.text")); // NOI18N
        jButtonInstallAll.setName("jButtonInstallAll"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(sfwWizardPageTitle1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanelProducts, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPanePackages, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 420, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonInstallAll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(sfwWizardPageTitle1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPanePackages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonInstallAll))
                    .add(jPanelProducts, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
    }//GEN-LAST:event_formAncestorAdded
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInstallAll;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPanePackages;
    private sfwinstaladorscript.components.SfwList sfwListProducts;
    private sfwinstaladorscript.components.SfwWizardPageTitle sfwWizardPageTitle1;
    // End of variables declaration//GEN-END:variables

    public void flowSetup(SfwInstaladorScriptView view) {
        try {
            this._currentindex = -1;
            this._finalexecuted = false;
            this._productpkg = new ArrayList();
            view.getBackButton().setEnabled(true);
            view.getNextButton().setEnabled(false);
            this.sfwListProducts.bind(Install.get_productsdetailinstall(), new SfwOracleProductDetail.SfwOracleProductDetailComparator());
            this.writeDefine();
            this.nextProductInstall();
        } catch (IOException ex) {
            ex.printStackTrace();
            view.getNextButton().setEnabled(false);
            this.jButtonInstallAll.setEnabled(false);
            this.jScrollPanePackages.setViewportView(null);
            JOptionPane.showMessageDialog(null,
                    Utils.getDefaultBundle(this).getString("JOptionPane.text.arqDefineErro")
                    + System.getProperty("line.separator")
                    + Utils.getDefaultBundle(this).getString("JOptionPane.text.error")
                    + ex.getMessage(),
                    Utils.getDefaultBundle(this).getString("JOptionPane.text.erro"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void nextClick(Hashtable wzPages, SfwInstaladorScriptView view) {

        File v_file_define;

        v_file_define = new File("temp" + System.getProperty("file.separator") + "define.sql");
        v_file_define.delete();

        System.exit(0);
    }

    public void backClick(Hashtable wzPages, SfwInstaladorScriptView view) {
        view.setWizardPage((JPanel) wzPages.get("wzValidator2"));
    }

    /**
     * Altera produto sendo instalado.
     * @param index √≠ndice do produto na lista.
     */
    public void nextProductInstall() {
        SfwOracleProductInstall v_sfworacleproduct_install;

        this._currentindex++;

        if (Install.get_productsdetailinstall().size() > this._currentindex) {
            this.sfwListProducts.setSelectedIndex(this._currentindex);
            v_sfworacleproduct_install = new SfwOracleProductInstall((SfwOracleProductDetail) Install.get_productsdetailinstall().get(this._currentindex), this, this._view);
            this._productpkg.add(v_sfworacleproduct_install);
            this.jScrollPanePackages.setViewportView((JPanel) v_sfworacleproduct_install);
            v_sfworacleproduct_install.setVisible(true);
        } else if (Install.get_productsdetailinstall().size() == this._currentindex) {
            this.jScrollPanePackages.setEnabled(false);
            this.sfwListProducts.setEnabled(true);
        }
    }

    /**
     * Altera produto sendo instalado.
     * @param index √≠ndice do produto na lista.
     */
    public void nextProductInstall(boolean toggled) {
        SfwOracleProductInstall v_sfworacleproduct_install;

        this._currentindex++;

        if (Install.get_productsdetailinstall().size() > this._currentindex) {
            this.sfwListProducts.setSelectedIndex(this._currentindex);

            v_sfworacleproduct_install = new SfwOracleProductInstall((SfwOracleProductDetail) Install.get_productsdetailinstall().get(this._currentindex), this, this._view, toggled);
            this._productpkg.add(v_sfworacleproduct_install);
            this.jScrollPanePackages.setViewportView((JPanel) v_sfworacleproduct_install);
            v_sfworacleproduct_install.setVisible(true);
        } else if (Install.get_productsdetailinstall().size() == this._currentindex) {
            this.jScrollPanePackages.setEnabled(false);
            this.sfwListProducts.setEnabled(true);
        }
    }

    @Action
    public void installAllClick() {

        TaskMonitor taskMonitor = new TaskMonitor(this._view.getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    _view.getBusyIconTimer().start();
                    if (_productpkg.size() > _currentindex) {
                        //((SfwOracleProductInstall) _productpkg.get(_currentindex)).setInstallButtons(false);
                        if (((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_pkgcomponent().size() > ((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_currentindex()) {
                            _view.getStatusAnimationLabel().setText(String.format(Utils.getDefaultBundle().getString("PackageInstall.installingpackage"), (((SfwOraclePackageInstall) ((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_pkgcomponent().get(((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_currentindex()))).getPackageName()));
                        }
                    }
                } else if ("done".equals(propertyName)) {
                    _view.getBusyIconTimer().stop();
                    _view.getStatusAnimationLabel().setIcon(_view.getIdleIcon());
                    _view.getStatusAnimationLabel().setText("");
                } else if ("message".equals(propertyName)) {
                } else if ("progress".equals(propertyName)) {
                    if (_productpkg.size() > _currentindex) {
                        // ((SfwOracleProductInstall) _productpkg.get(_currentindex)).setInstallButtons(false);
                        if (((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_pkgcomponent().size() > ((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_currentindex()) {
                            _view.getStatusAnimationLabel().setText(String.format(Utils.getDefaultBundle().getString("PackageInstall.installingpackage"), (((SfwOraclePackageInstall) ((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_pkgcomponent().get(((SfwOracleProductInstall) _productpkg.get(_currentindex)).get_currentindex()))).getPackageName()));
                        }
                    } else if (_productpkg.size() == _currentindex) {
                        _view.getStatusAnimationLabel().setText(Utils.getDefaultBundle().getString("PackageInstall.finalvalidation"));
                    }
                }
            }
        });

        this._installpackagetask = new Task(this._view.getApplication()) {

            @Override
            protected Object doInBackground() throws Exception {

                Utils.setBusyCursor();

                for (int i = _currentindex; i < Install.get_productsdetailinstall().size(); i++) {
                    for (int j = ((SfwOracleProductInstall) _productpkg.get(i)).get_currentindex(); j < ((SfwOracleProductInstall) _productpkg.get(i)).get_pkgcomponent().size(); j++) {
                        if (((SfwOracleProductInstall) _productpkg.get(i)).installPackage()) {
                            this.firePropertyChange("progress", null, null);
                        } else {
                            //((SfwOracleProductInstall) _productpkg.get(i)).setInstallButtons();
                            setInstallButtons();

                            this.cancel(true);
                            Utils.setDefaultCursor();
                            return null;
                        }
                    }
                    //((SfwOracleProductInstall) _productpkg.get(i)).setInstallButtons();
                }
                executeFinalPackage();
                CMschema();
                SendLog();
                setInstallButtons();

                Utils.setDefaultCursor();
                return null;
            }
        };

        taskMonitor.setForegroundTask(this._installpackagetask);
        this._view.getBackButton().setEnabled(false);
        this._view.getNextButton().setText(Utils.getDefaultBundle().getString("PackageInstall.buttonfinal"));
        this._view.getNextButton().setEnabled(false);
        this.jButtonInstallAll.setEnabled(false);
        this._installpackagetask.execute();
    }

    /**
     * Retorna se a instalaÁ„o foi totalmente completada.
     * @return TRUE- finalizada FALSE- n√£o finalizada
     */
    public boolean isFinished() {
        if (this._currentindex == Install.get_productsdetailinstall().size() && this._finalexecuted) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Retorna se a instalaÁ„o dos produtos foi completada.
     * @return TRUE- finalizada FALSE- n„o finalizada
     */
    public boolean isProductsFinished() {
        if (this._currentindex == Install.get_productsdetailinstall().size()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Altera estado dos bot√µes de instala√ß√£o.
     */
    public void setInstallButtons() {
        if (this.isFinished()) {
            this.jButtonInstallAll.setEnabled(false);
            this._view.getNextButton().setEnabled(true);
            //this.createProfile();
        } else {
            this.jButtonInstallAll.setEnabled(true);
            this._view.getNextButton().setEnabled(false);
        }
    }

    /**
     * Procedimento para execuÁ„o de pacote final com grants, compilaÁ„o e validaÁıes.
     */
    public void executeFinalPackage() {
        File v_file_extraction_point;
        PackageFinal v_packagefinal_pkt;
        File v_file_comparer_tmp = new File("temp" + System.getProperty("file.separator") + "basecomparer");

        Utils.setBusyCursor();

        if (this.isProductsFinished()) {
            v_packagefinal_pkt = Install.get_packagelist().get_final_package();

            if (v_packagefinal_pkt != null) {
                v_file_extraction_point = new File("temp" + System.getProperty("file.separator") + "final");
                if (!v_file_extraction_point.exists()) {
                    v_file_extraction_point.mkdirs();
                }

                try {

                    //copia carga de comparadores de base para o diretorio do pacote final
                    //this.copyComparers(v_file_extraction_point);

                    //gerar arquivos dinamicos do final
                    this.createInvalidsSql(v_file_extraction_point);
                    //
                    this.createLoadJava(v_file_extraction_point);
                    //this.createValidaSinonimo(v_file_extraction_point);
                    this.createBrokerReport(v_file_extraction_point);
                    //
                    this.createLoadApi(v_file_extraction_point);
                    //this.createValidaProcedureEnviaEmail(v_file_extraction_point);
                    //this.createComparaBase(v_file_extraction_point);
                    
                    this.createRebuildTablespaces(v_file_extraction_point);

                    v_packagefinal_pkt.execute(v_file_extraction_point);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }

                if (v_file_comparer_tmp.exists()) {
                    Utils.deleteDirectory(v_file_comparer_tmp);
                }

                Utils.deleteDirectory(v_file_extraction_point);
            }

            Utils.setDefaultCursor();
            _finalexecuted = true;
            setInstallButtons();
        }
    }

    /**
     * Copia comparadores de base para o diret√≥rio do final.
     * @param p_file_extraction_point Ponto de extra√ß√£o.
     * @throws java.io.IOException
     */
    private void copyComparers(File p_file_extraction_point) throws IOException {
        File[] v_file_list_comparer;
        File v_file_comparer, v_file_comparer_copy, v_file_comparer_tmp = null;
        String v_string_reader;
        BufferedReader v_bufferedreader_comp;
        BufferedWriter v_bufferedwriter_compcopy;

        //copia carga de comparadores de base para o diretorio do pacote final
        v_file_comparer_tmp = new File("temp" + System.getProperty("file.separator") + "basecomparer");

        if (v_file_comparer_tmp.exists()) {
            v_file_list_comparer = v_file_comparer_tmp.listFiles();
            for (int i = 0; i < v_file_list_comparer.length; i++) {
                v_file_comparer = (File) v_file_list_comparer[i];
                v_file_comparer_copy = new File(p_file_extraction_point, v_file_comparer.getName());

                if (!v_file_comparer_copy.exists()) {
                    v_file_comparer_copy.createNewFile();
                }

                v_bufferedreader_comp = new BufferedReader(new FileReader(v_file_comparer));
                v_bufferedwriter_compcopy = new BufferedWriter(new FileWriter(v_file_comparer_copy));

                // faz a copia linha a linha para retirar os spool padrao da carga
                v_string_reader = v_bufferedreader_comp.readLine();
                while (v_string_reader != null) {
                    if (!v_string_reader.toUpperCase().startsWith("SPOOL")) {
                        v_bufferedwriter_compcopy.write(v_string_reader);
                        v_bufferedwriter_compcopy.newLine();
                    }

                    v_string_reader = v_bufferedreader_comp.readLine();
                }

                v_bufferedreader_comp.close();
                v_bufferedwriter_compcopy.close();
            }
        }
    }

    /**
     * Cria arquivo invalids.sql para compila√ß√£o de objetos inv√°lidos.
     * @param extractionpoint
     * @throws java.io.IOException
     */
    private void createInvalidsSql(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleDefineUser v_sfworacledefineuser_current;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_invalid = new File(extractionpoint, "invalids.sql");
        BufferedWriter v_bufferedwriter_invalid = null;

        try {
            if (!v_file_invalid.exists()) {
                v_file_invalid.createNewFile();
            }

            v_bufferedwriter_invalid = new BufferedWriter(new FileWriter(v_file_invalid));

            // duas iteracoes de compilacao
            for (int i = 0; i < 2; i++) {
                v_iterator_it = Install.get_productsdetail().iterator();
                while (v_iterator_it.hasNext()) {
                    v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                    v_bufferedwriter_invalid.write("prompt");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt Connecting to " + v_sfworacleproductdetail_current.getUser() + "/" + this.retornaSenha(v_sfworacleproductdetail_current.getPassword()) + "@" + Install.get_tns());
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt ==================================================================");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("connect " + v_sfworacleproductdetail_current.getUser() + "/" + v_sfworacleproductdetail_current.getPassword() + "@" + Install.get_tns());
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("set serveroutput on size 1000000");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt Creating or Replacing procedure PRC_COMPILA_INVALIDO...");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("@prc_compila_invalido.sql");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt Executing PRC_COMPILA_INVALIDO...");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("prompt");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.write("exec prc_compila_invalido;");
                    v_bufferedwriter_invalid.newLine();
                    v_bufferedwriter_invalid.newLine();
                }

                v_iterator_it = Install.get_productdefine().iterator();
                while (v_iterator_it.hasNext()) {
                    v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_it.next();

                    if (Product.productExists(v_sfworacledefineuser_current.getUser(), v_sfworacledefineuser_current.getPassword(), v_sfworacledefineuser_current.getProduct().get_code())) {
                        v_bufferedwriter_invalid.write("prompt");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt Connecting to " + v_sfworacledefineuser_current.getUser() + "/" + this.retornaSenha(v_sfworacledefineuser_current.getPassword()) + "@" + Install.get_tns());
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt ==================================================================");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("connect " + v_sfworacledefineuser_current.getUser() + "/" + v_sfworacledefineuser_current.getPassword() + "@" + Install.get_tns());
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt Creating or Replacing procedure PRC_COMPILA_INVALIDO...");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("@prc_compila_invalido.sql");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("prompt Executing PRC_COMPILA_INVALIDO...");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.write("exec prc_compila_invalido;");
                        v_bufferedwriter_invalid.newLine();
                        v_bufferedwriter_invalid.newLine();
                    }
                }
            }

            v_bufferedwriter_invalid.close();

        } catch (IOException ex) {
            throw ex;
        } finally {
            try {
                v_bufferedwriter_invalid.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * Escreve arquivo DEFINE no temp para instalaÁ„o dos pacotes.
     */
    private void writeDefine() throws IOException {
        String v_string_line;
        Iterator v_iterator_it;
        FileReader v_filereader_frappend;
        BufferedReader v_bufferedreader_bappend;
        SfwOracleDefineUser v_sfworacledefineuser_current;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_user_append = new File("define_user_append.txt");
        File v_file_temp = new File("temp");
        File v_file_define = new File(v_file_temp, "define.sql");
        BufferedWriter v_bufferedwriter_define = null;

        try {
            if (!v_file_temp.exists()) {
                v_file_temp.mkdir();
            }
            if (!v_file_define.exists()) {
                v_file_define.createNewFile();
            }

            v_bufferedwriter_define = new BufferedWriter(new FileWriter(v_file_define));


            v_bufferedwriter_define.write("-- Constante para saber se È primeira instalaÁ„o ou n„o!");
            v_bufferedwriter_define.newLine();
            if (SfwWizardSetup.jRadioPrimeira.isSelected()) {
                v_bufferedwriter_define.write("DEFINE PRIMEIRA_INSTALACAO = S");
            } else {
                v_bufferedwriter_define.write("DEFINE PRIMEIRA_INSTALACAO = N");
            }
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Define para sigla do paÌs");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE SIGLA_PAIS = BR");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Constante do usu·rio sombra");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE USUARIO_SOMBRA_USER = " + Utils.nvl(Profile.getUsuariosombra(), "USUARIO_SOMBRA_USER"));
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE USUARIO_SOMBRA_PASS = " + Utils.nvl(Profile.getSenhasombra(), "USUARIO_SOMBRA_PASS"));
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Constante do Role Softway");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE ROLE_SOFTWAY = " + Utils.nvl(Install.get_rolesfw(), "ROLE_SOFTWAY"));
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Constantes para Conex„o");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE TNS = " + Install.get_tns());
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Maquina");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE USER_MACHINE = SERVIDOR");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("-- Usu·rios Padr„o");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE REGINT_USER = REGINT_USER");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE RAF_USER = RAF_USER");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE RECOF_USER = ''");
            v_bufferedwriter_define.newLine();
            v_bufferedwriter_define.write("DEFINE IMPORT_INT_USER = IMPORT_INT_USER");
            v_bufferedwriter_define.newLine();

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                v_bufferedwriter_define.write("DEFINE " + v_sfworacleproductdetail_current.getProduct().get_defineprefix() + "_USER = " + v_sfworacleproductdetail_current.getUser());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE " + v_sfworacleproductdetail_current.getProduct().get_defineprefix() + "_PASS = " + v_sfworacleproductdetail_current.getPassword());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.newLine();

                // se for InOut coloca alÈm do padr„o o user/pass especifico
                if (v_sfworacleproductdetail_current.getProduct().get_name().equals("INOUT_SYS")) {
                    v_bufferedwriter_define.write("DEFINE IO_USER = " + v_sfworacleproductdetail_current.getUser());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE IO_PASS = " + v_sfworacleproductdetail_current.getPassword());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.newLine();
                }
            }

            v_iterator_it = Install.get_productdefine().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_it.next();
                v_bufferedwriter_define.write("DEFINE " + v_sfworacledefineuser_current.getProduct().get_defineprefix() + "_USER = " + v_sfworacledefineuser_current.getUser());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE " + v_sfworacledefineuser_current.getProduct().get_defineprefix() + "_PASS = " + v_sfworacledefineuser_current.getPassword());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.newLine();

                // se for InOut coloca alÈm do padr„o o user/pass especifico
                if (v_sfworacledefineuser_current.getProduct().get_name().equals("INOUT_SYS")) {
                    v_bufferedwriter_define.write("DEFINE IO_USER = " + v_sfworacledefineuser_current.getUser());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE IO_PASS = " + v_sfworacledefineuser_current.getPassword());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.newLine();
                }
            }

            if (v_file_user_append.exists()) {
                v_filereader_frappend = new FileReader(v_file_user_append);
                v_bufferedreader_bappend = new BufferedReader(v_filereader_frappend);

                v_string_line = v_bufferedreader_bappend.readLine();
                while (v_string_line != null) {
                    v_bufferedwriter_define.write(v_string_line);
                    v_bufferedwriter_define.newLine();
                    v_string_line = v_bufferedreader_bappend.readLine();
                }
                v_bufferedwriter_define.newLine();
            }

            v_bufferedwriter_define.write("-- Constantes de Tablespace");
            v_bufferedwriter_define.newLine();

            v_iterator_it = Install.get_productsdetailinstall().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_4K = " + v_sfworacleproductdetail_current.getData4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_64K = " + v_sfworacleproductdetail_current.getData4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_128K = " + v_sfworacleproductdetail_current.getData4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_512K = " + v_sfworacleproductdetail_current.getData4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_1M = " + v_sfworacleproductdetail_current.getData4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_4K = " + v_sfworacleproductdetail_current.getIndex4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_64K = " + v_sfworacleproductdetail_current.getIndex4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_128K = " + v_sfworacleproductdetail_current.getIndex4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_512K = " + v_sfworacleproductdetail_current.getIndex4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail_current.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_1M = " + v_sfworacleproductdetail_current.getIndex4k());
                v_bufferedwriter_define.newLine();
                v_bufferedwriter_define.newLine();
            }

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                SfwOracleProductDetail v_sfworacleproductdetail = (SfwOracleProductDetail) v_iterator_it.next();
                if (v_sfworacleproductdetail.getProduct().get_code().equals("1000")
                        || v_sfworacleproductdetail.getProduct().get_code().equals("500")) {
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_4K = " + v_sfworacleproductdetail.getData4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_64K = " + v_sfworacleproductdetail.getData4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_128K = " + v_sfworacleproductdetail.getData4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_512K = " + v_sfworacleproductdetail.getData4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_DATA_1M = " + v_sfworacleproductdetail.getData4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_4K = " + v_sfworacleproductdetail.getIndex4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_64K = " + v_sfworacleproductdetail.getIndex4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_128K = " + v_sfworacleproductdetail.getIndex4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_512K = " + v_sfworacleproductdetail.getIndex4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.write("DEFINE SFW" + Utils.nvl(v_sfworacleproductdetail.getProduct().get_tablespaceprefix(), "", "_", "") + "_INDEX_1M = " + v_sfworacleproductdetail.getIndex4k());
                    v_bufferedwriter_define.newLine();
                    v_bufferedwriter_define.newLine();
                }
            }

            v_bufferedwriter_define.write("-- Constante para Login GenÈrico");
            v_bufferedwriter_define.newLine();

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                v_bufferedwriter_define.write("DEFINE COD_SISTEMA_" + v_sfworacleproductdetail_current.getProduct().get_defineprefix() + " = " + Utils.nvl(v_sfworacleproductdetail_current.getCodSistema(), "NULL"));
                v_bufferedwriter_define.newLine();
            }

            v_iterator_it = Install.get_productdefine().iterator();
            while (v_iterator_it.hasNext()) {
                SfwOracleDefineUser v_sfworacledefineuser = (SfwOracleDefineUser) v_iterator_it.next();
                v_bufferedwriter_define.write("DEFINE COD_SISTEMA_" + v_sfworacledefineuser.getProduct().get_defineprefix() + " = " + Utils.nvl(v_sfworacledefineuser.getProduct().get_code(), "NULL"));
                v_bufferedwriter_define.newLine();
            }

            v_bufferedwriter_define.close();

        } catch (IOException ex) {
            throw ex;
        } finally {
            try {
                v_bufferedwriter_define.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * cria arquivo loadsoftcomexjava.bat para inicializa√ß√£o do pacote JAVA para envio do email
     * @param extractionpoint
     * @throws IOException
     */
    private void createLoadJava(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_load_java = new File(extractionpoint, "loadsoftcomexjava.bat");
        BufferedWriter v_bufferedwriter_load_java = null;

        try {
            if (!v_file_load_java.exists()) {
                v_file_load_java.createNewFile();
            }
            v_bufferedwriter_load_java = new BufferedWriter(new FileWriter(v_file_load_java));

            v_iterator_it = Install.get_productsdetail().iterator();

            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                if (v_sfworacleproductdetail_current.getProduct().get_name().equals("SOFTCOMEX") && v_sfworacleproductdetail_current.isFirstInstall()) {
                    String user = v_sfworacleproductdetail_current.getUser();
                    String password = v_sfworacleproductdetail_current.getPassword();
                    String tns = Install.get_tns();
                    v_bufferedwriter_load_java.write("echo Carregando bibliotecas Java no Softcomex...");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo ==============================================");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo.");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo Executando activation.jar ...");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo on");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("CALL loadjava -user " + user + "/" + password + "@" + tns + " ." + System.getProperty("file.separator") + "lib" + System.getProperty("file.separator") + "activation.jar");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo off");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo.");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo Executando mail.jar ...");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo on");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("CALL loadjava -user " + user + "/" + password + "@" + tns + " ." + System.getProperty("file.separator") + "lib" + System.getProperty("file.separator") + "mail.jar");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo off");
                    v_bufferedwriter_load_java.newLine();
                    v_bufferedwriter_load_java.write("echo.");
                    v_bufferedwriter_load_java.newLine();
                    break;
                }
            }
            v_bufferedwriter_load_java.close();
        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_load_java.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * cria o arquivo sinonimos.sql para compilar a procedure de valida√ßao de sin√¥nimos e FKs
     * @param extractionpoint
     * @throws IOException
     */
    private void createValidaSinonimo(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_sinonimo = new File(extractionpoint, "sinonimos.sql");
        BufferedWriter v_bufferedwriter_sinonimo = null;

        try {
            if (!v_file_sinonimo.exists()) {
                v_file_sinonimo.createNewFile();
            }

            v_bufferedwriter_sinonimo = new BufferedWriter(new FileWriter(v_file_sinonimo));

            v_iterator_it = Install.get_productsdetailinstall().iterator();

            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();

                String user = v_sfworacleproductdetail_current.getUser();
                String password = v_sfworacleproductdetail_current.getPassword();
                String tns = Install.get_tns();

                v_bufferedwriter_sinonimo.write("prompt");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt ==================================================================");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("connect " + user + "/" + password + "@" + tns);
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("set serveroutput on size 1000000");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt Creating or Replacing procedure SFW_VALIDA_SINONIMO...");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("@sfw_valida_sinonimo.sql");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt Executing SFW_VALIDA_SINONIMO...");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("prompt");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.write("exec sfw_valida_sinonimo;");
                v_bufferedwriter_sinonimo.newLine();
                v_bufferedwriter_sinonimo.newLine();
            }
        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_sinonimo.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * cria o arquivo sinonimos.sql para compilar a procedure de valida√ßao de sin√¥nimos e FKs
     * @param extractionpoint
     * @throws IOException
     */
    private void createComparaBase(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_comparer;
        File v_file_sinonimo = new File(extractionpoint, "comparabase.sql");
        BufferedWriter v_bufferedwriter_compare = null;

        try {
            if (!v_file_sinonimo.exists()) {
                v_file_sinonimo.createNewFile();
            }

            v_bufferedwriter_compare = new BufferedWriter(new FileWriter(v_file_sinonimo));

            v_iterator_it = Install.get_productsdetailinstall().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();

                v_file_comparer = new File(extractionpoint, v_sfworacleproductdetail_current.getProduct().get_shortname().toLowerCase() + "_comparer.sql");

                if (v_file_comparer.exists()) {
                    String user = v_sfworacleproductdetail_current.getUser();
                    String password = v_sfworacleproductdetail_current.getPassword();
                    String tns = Install.get_tns();

                    v_bufferedwriter_compare.write("prompt");
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("prompt Comparing " + user + "/" + this.retornaSenha(password) + "@" + tns);
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("prompt ==================================================================");
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("define USER = " + user);
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("define PASS = " + password);
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("define TNS = " + tns);
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("SPOOL " + v_sfworacleproductdetail_current.getProduct().get_name().toLowerCase().replace("_", "") + "_comparacao.log");
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("@" + v_sfworacleproductdetail_current.getProduct().get_shortname().toLowerCase() + "_comparer.sql");
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.write("Spool off");
                    v_bufferedwriter_compare.newLine();
                    v_bufferedwriter_compare.newLine();
                }
            }
        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_compare.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Valida de a procedure envia e-mail da base gen√©rica esta valida
     * @param extractionpoint
     * @throws IOException
     */
    private void createValidaProcedureEnviaEmail(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_enviaemail = new File(extractionpoint, "envia_email.sql");

        BufferedWriter v_bufferedwriter_validaprcenviaemail = null;

        try {

            if (!v_file_enviaemail.exists()) {
                v_file_enviaemail.createNewFile();
            }

            v_bufferedwriter_validaprcenviaemail = new BufferedWriter(new FileWriter(v_file_enviaemail));

            v_iterator_it = Install.get_productsdetailinstall().iterator();

            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();
                if (v_sfworacleproductdetail_current.getProduct().get_name().equals("SOFTCOMEX")) {
                    String user = v_sfworacleproductdetail_current.getUser();
                    String password = v_sfworacleproductdetail_current.getPassword();
                    String tns = Install.get_tns();

                    v_bufferedwriter_validaprcenviaemail.write("prompt");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt ==================================================================");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("connect " + user + "/" + password + "@" + tns);
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("set serveroutput on size 1000000");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt valida procedure envia_email...");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("@sfw_valida_prc_envia_email.sql");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt Executing procedure sfw_valida_prc_envia_email...");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("exec sfw_valida_prc_envia_email;");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt Deleting procedure sfw_valida_prc_envia_email...");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("prompt");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.write("drop procedure sfw_valida_prc_envia_email;");
                    v_bufferedwriter_validaprcenviaemail.newLine();
                    v_bufferedwriter_validaprcenviaemail.newLine();

                    break;
                }
            }
            v_bufferedwriter_validaprcenviaemail.close();
        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_validaprcenviaemail.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /***
     * cria o arquivo brokerreport.sql para rodar o arquivo broker_report.sql para todos os produtos
     * @param extractionpoint
     * @throws IOException
     */
    private void createBrokerReport(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleDefineUser v_sfworacledefineuser_current;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_broker = new File(extractionpoint, "brokerreport.sql");
        BufferedWriter v_bufferedwriter_broker = null;

        try {
            if (!v_file_broker.exists()) {
                v_file_broker.createNewFile();
            }

            v_bufferedwriter_broker = new BufferedWriter(new FileWriter(v_file_broker));

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();

                String user = v_sfworacleproductdetail_current.getUser();
                String password = v_sfworacleproductdetail_current.getPassword();
                String tns = Install.get_tns();

                v_bufferedwriter_broker.write("prompt");
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("prompt ==================================================================");
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("connect " + user + "/" + password + "@" + tns);
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("prompt");
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("prompt Executing Product Report...");
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.write("@broker_report.sql");
                v_bufferedwriter_broker.newLine();
                v_bufferedwriter_broker.newLine();
            }

            v_iterator_it = Install.get_productdefine().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_it.next();

                if (v_sfworacledefineuser_current.getProduct().get_name().equals("SOFTCOMEX")) {
                    String user = v_sfworacledefineuser_current.getUser();
                    String password = v_sfworacledefineuser_current.getPassword();
                    String tns = Install.get_tns();

                    if (Product.productExists(v_sfworacledefineuser_current.getUser(), v_sfworacledefineuser_current.getPassword(), v_sfworacledefineuser_current.getProduct().get_code())) {
                        v_bufferedwriter_broker.write("prompt");
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("prompt ==================================================================");
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("connect " + user + "/" + password + "@" + tns);
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("prompt");
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("prompt Executing Product Report...");
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.write("@broker_report.sql");
                        v_bufferedwriter_broker.newLine();
                        v_bufferedwriter_broker.newLine();
                    }
                }
            }

        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_broker.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    /***
     * cria o arquivo carregaapi.sql para rodar o arquivo carrega_api.sql para todos os produtos
     * @param extractionpoint
     * @throws IOException
     */
    private void createLoadApi(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleDefineUser v_sfworacledefineuser_current;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_api = new File(extractionpoint, "carregaapi.sql");
        BufferedWriter v_bufferedwriter_api = null;

        try {
            if (!v_file_api.exists()) {
                v_file_api.createNewFile();
            }

            v_bufferedwriter_api = new BufferedWriter(new FileWriter(v_file_api));

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();

                String user = v_sfworacleproductdetail_current.getUser();
                String password = v_sfworacleproductdetail_current.getPassword();
                String tns = Install.get_tns();

                v_bufferedwriter_api.write("prompt");
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("prompt ==================================================================");
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("connect " + user + "/" + password + "@" + tns);
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("prompt");
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("prompt Loading APIs...");
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.write("@carrega_api.sql");
                v_bufferedwriter_api.newLine();
                v_bufferedwriter_api.newLine();
            }

            v_iterator_it = Install.get_productdefine().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_it.next();

                if (v_sfworacledefineuser_current.getProduct().get_name().equals("SOFTCOMEX")) {
                    String user = v_sfworacledefineuser_current.getUser();
                    String password = v_sfworacledefineuser_current.getPassword();
                    String tns = Install.get_tns();

                    if (Product.productExists(v_sfworacledefineuser_current.getUser(), v_sfworacledefineuser_current.getPassword(), v_sfworacledefineuser_current.getProduct().get_code())) {
                        v_bufferedwriter_api.write("prompt");
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("prompt ==================================================================");
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("connect " + user + "/" + password + "@" + tns);
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("prompt");
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("prompt prompt Loading APIs....");
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.write("@carrega_api.sql");
                        v_bufferedwriter_api.newLine();
                        v_bufferedwriter_api.newLine();
                    }
                }
            }

        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_api.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    
        /***
     * cria o arquivo rebuildtablespace.sql para rodar o arquivo rebuild_tablespace.sql para todos os produtos
     * @param extractionpoint
     * @throws IOException
     */
    private void createRebuildTablespaces(File extractionpoint) throws IOException {
        Iterator v_iterator_it;
        SfwOracleDefineUser v_sfworacledefineuser_current;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        File v_file_rebuild = new File(extractionpoint, "rebuildtablespace.sql");
        BufferedWriter v_bufferedwriter_rebuild = null;

        try {
            if (!v_file_rebuild.exists()) {
                v_file_rebuild.createNewFile();
            }

            v_bufferedwriter_rebuild = new BufferedWriter(new FileWriter(v_file_rebuild));

            v_iterator_it = Install.get_productsdetail().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_it.next();

                String user = v_sfworacleproductdetail_current.getUser();
                String password = v_sfworacleproductdetail_current.getPassword();
                String tns = Install.get_tns();

                v_bufferedwriter_rebuild.write("prompt");
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("prompt ==================================================================");
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("connect " + user + "/" + password + "@" + tns);
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("prompt");
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("prompt Rebuilding tablespaces...");
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.write("@rebuild_tablespace.sql");
                v_bufferedwriter_rebuild.newLine();
                v_bufferedwriter_rebuild.newLine();
            }

            v_iterator_it = Install.get_productdefine().iterator();
            while (v_iterator_it.hasNext()) {
                v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_it.next();

                if (v_sfworacledefineuser_current.getProduct().get_name().equals("SOFTCOMEX")) {
                    String user = v_sfworacledefineuser_current.getUser();
                    String password = v_sfworacledefineuser_current.getPassword();
                    String tns = Install.get_tns();

                    if (Product.productExists(v_sfworacledefineuser_current.getUser(), v_sfworacledefineuser_current.getPassword(), v_sfworacledefineuser_current.getProduct().get_code())) {
                        v_bufferedwriter_rebuild.write("prompt");
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("prompt Connecting to " + user + "/" + this.retornaSenha(password) + "@" + tns);
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("prompt ==================================================================");
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("connect " + user + "/" + password + "@" + tns);
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("prompt");
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("prompt Rebuilding tablespaces....");
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.write("@rebuild_tablespace.sql");
                        v_bufferedwriter_rebuild.newLine();
                        v_bufferedwriter_rebuild.newLine();
                    }
                }
            }

        } catch (IOException e) {
            throw e;
        } finally {
            try {
                v_bufferedwriter_rebuild.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public boolean CMschema() {
        Iterator v_iterator_it;
        OracleConnection v_conn = new OracleConnection();
        try {

            v_conn.connectBeforeAfterValidations();
            v_conn.createTableSfwCmSchema();

            for (int i = 0; i < Install.get_productsdetailinstall().size(); i++) {
                SfwOracleProductDetail v_sfworacleproduct_install = (SfwOracleProductDetail) Install.get_productsdetailinstall().get(i);
                v_conn.insertCMschema(v_sfworacleproduct_install);
            }
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        } finally {
            v_conn.Close();
        }
    }

    public void SendLog() throws FileNotFoundException, IOException {
        String arquivo = "";
        String v_string_date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        String v_string_instalacao = new SimpleDateFormat("dd/MM/yyyy H:mm:ss").format(new Date());
        File v_file_log = new File("log");
        File[] v_arrayfile_log = v_file_log.listFiles();
        List<String[]> v_string_product = new ArrayList<String[]>();
        StringBuilder v_sb_mensagem = null;
        //
        for (int i = 0; i < v_arrayfile_log.length; i++) {
            if (v_arrayfile_log[i].isDirectory()) {
                if (v_arrayfile_log[i].getPath().contains(v_string_date)) {
                    if (new File(v_string_date + ".zip").exists()) {
                        new File(v_string_date + ".zip").delete();
                    }
                    arquivo = Utils.zipFiles(v_arrayfile_log[i].getPath(), "log", v_string_date + ".zip");
                    Iterator v_iterator_it = Install.get_productsdetail().iterator();
                    //
                    while (v_iterator_it.hasNext()) {
                        SfwOracleProductDetail v_sfworacledefineuser = (SfwOracleProductDetail) v_iterator_it.next();
                        v_string_product.add(new String[]{v_sfworacledefineuser.getUser(), v_sfworacledefineuser.getProduct().getInstalledversion(), v_sfworacledefineuser.getProduct().getSelectedversion()});
                    }
                    v_sb_mensagem = new StringBuilder();
                    v_sb_mensagem.append("<table width=\"50%\"><caption>Instalador de Scripts</caption>");
                    //
                    v_sb_mensagem.append("<thead><tr><th colspan=\"3\">Usu·rio: " + Utils.nvl(System.getProperty("user.name"), "Administrador") + "</th></tr>");
                    v_sb_mensagem.append("<tr><th>TNS de InstalaÁ„o</th>");
                    //
                    v_sb_mensagem.append("<th>Sigla</th>");
                    v_sb_mensagem.append("<th>Data da InstalaÁ„o</th>");
                    v_sb_mensagem.append("<tr><td align=\"center\">" + Install.get_tns() + "</td>\n");
                    v_sb_mensagem.append("<td align=\"center\">" + Install.get_shortname() + "</td>\n");
                    v_sb_mensagem.append("<td align=\"center\">" + v_string_instalacao + "</td></tr>\n");
                    //
                    v_sb_mensagem.append("<th>Usu·rios Instalados</th>\n");
                    v_sb_mensagem.append("<th>Vers„o Anterior</th>\n");
                    v_sb_mensagem.append("<th>Vers„o Instalada</th></tr></thead>\n");
                    for (int j = 0; j < v_string_product.size(); j++) {
                        v_sb_mensagem.append("<tr><td align=\"center\">" + v_string_product.get(j)[0] + "</td>");
                        v_sb_mensagem.append("<td align=\"center\">" + v_string_product.get(j)[1] + "</td>");
                        v_sb_mensagem.append("<td align=\"center\">" + v_string_product.get(j)[2] + "</td>");
                    }
                    v_sb_mensagem.append("</tr>\n");
                    v_sb_mensagem.append("</tbody></table><br><br>\n");
                }
            }
        }
        try {
            Mail mail = new Mail();
            Utils.ProxyServer(false);
            try {
                mail.post(v_sb_mensagem, "cm.produto@softwaysa.com", new File(arquivo));
            } catch (Exception e) {
            }
            Utils.ProxyServer(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * MÈtodo para esconder a senha dos logs.
     * @param senha
     * @return 
     */
    private String retornaSenha(String senha) {
        String n_s_senhaAsterisco = "";
        for (int i = 0; i < senha.length(); i++) {
            n_s_senhaAsterisco += "*";
        }
        return n_s_senhaAsterisco;
    }
}
