/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SfwWizardProductCompatibility2.java
 *
 * Created on Jun 15, 2011, 1:14:23 PM
 */
package sfwinstaladorscript.oracleinstallation;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sfwinstaladorscript.objects.ProductCompatibility;

/**
 *
 * @author jopaulo
 */
public class SfwWizardProductCompatibility2 extends javax.swing.JPanel {

    private ProductCompatibility _compatibility;

    /** Creates new form SfwWizardProductCompatibility */
    public SfwWizardProductCompatibility2(ProductCompatibility compatibility) {
        this._compatibility = compatibility;
        initComponents();
        jTextCompativel.setText(this._compatibility.getVersioncompability());
        jTextVersaoEscolhida.setText(this._compatibility.getVersion());
        jLabelProduto.setText(this._compatibility.getProduct().get_label());
        ImageIcon v_icon_product = new ImageIcon("icon\\" + this._compatibility.getProduct().get_icon());
        jLabelProduto.setIcon(v_icon_product);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextCompativel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextVersaoEscolhida = new javax.swing.JTextField();
        jLabelCompativel = new javax.swing.JLabel();
        jLabelProduto = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(360, 40));
        setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardProductCompatibility2.class);
        jTextCompativel.setBackground(resourceMap.getColor("jTextCompativel.background")); // NOI18N
        jTextCompativel.setEditable(false);
        jTextCompativel.setFont(resourceMap.getFont("jTextCompativel.font")); // NOI18N
        jTextCompativel.setForeground(resourceMap.getColor("jTextCompativel.foreground")); // NOI18N
        jTextCompativel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCompativel.setText(resourceMap.getString("jTextCompativel.text")); // NOI18N
        jTextCompativel.setName("jTextCompativel"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextVersaoEscolhida.setEditable(false);
        jTextVersaoEscolhida.setFont(resourceMap.getFont("jTextVersaoEscolhida.font")); // NOI18N
        jTextVersaoEscolhida.setForeground(resourceMap.getColor("jTextVersaoEscolhida.foreground")); // NOI18N
        jTextVersaoEscolhida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVersaoEscolhida.setName("jTextVersaoEscolhida"); // NOI18N

        jLabelCompativel.setText(resourceMap.getString("jLabelCompativel.text")); // NOI18N
        jLabelCompativel.setName("jLabelCompativel"); // NOI18N

        jLabelProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProduto.setText(resourceMap.getString("jLabelProduto.text")); // NOI18N
        jLabelProduto.setName("jLabelProduto"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextVersaoEscolhida, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelCompativel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCompativel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompativel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVersaoEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCompativel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabelProduto))
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 46);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCompativel;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCompativel;
    private javax.swing.JTextField jTextVersaoEscolhida;
    // End of variables declaration//GEN-END:variables
}
