/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SfwWizardInstalledProduct.java
 *
 * Created on Nov 24, 2008, 11:49:28 AM
 */
package sfwinstaladorscript.oracleinstallation;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sfwinstaladorscript.Install;
import sfwinstaladorscript.Profile;
import sfwinstaladorscript.SfwInstaladorScriptView;
import sfwinstaladorscript.Utils;
import sfwinstaladorscript.oracleinstallation.components.SfwOracleDefineUser;
import sfwinstaladorscript.interfaces.SfwWizardPage;
import sfwinstaladorscript.objects.Product;
import sfwinstaladorscript.objects.ProductProfileDefine;

/**
 * Tela para especificar usuários de produtos não selecionados para instalação.
 */
public class SfwWizardOracleProduct2 extends javax.swing.JPanel implements SfwWizardPage {

    private SfwInstaladorScriptView _view;
    private ArrayList _products;
    private ArrayList _productsdefine;

    /** Creates new form SfwWizardInstalledProduct */
    public SfwWizardOracleProduct2(SfwInstaladorScriptView view, ArrayList products) {
        initComponents();

        this._view = view;
        this._products = products;

        this.jTextFieldRoleSfw.setText("RTR" + Install.get_shortname());
        this.jTextFieldRoleSfw.setToolTipText(Utils.getDefaultBundle().getString("Database.msghint"));

        this.jTextFieldUsuarioSombra.setText("STR" + Install.get_shortname());
        this.jTextFieldSenhaSombra.setText("TR" + Install.get_shortname());

        jCheckBoxUseRole.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfwWizardPageTitle1 = new sfwinstaladorscript.components.SfwWizardPageTitle();
        jScrollPaneProductDefine = new javax.swing.JScrollPane();
        jPanelProductDefine = new javax.swing.JPanel();
        jTextFieldRoleSfw = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxUseRole = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuarioSombra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSenhaSombra = new javax.swing.JPasswordField();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(605, 378));

        sfwWizardPageTitle1.setName("sfwWizardPageTitle1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardOracleProduct2.class);
        sfwWizardPageTitle1.setSubtitulo(resourceMap.getString("sfwWizardPageTitle1.subtitulo")); // NOI18N
        sfwWizardPageTitle1.setTitulo(resourceMap.getString("sfwWizardPageTitle1.titulo")); // NOI18N

        jScrollPaneProductDefine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jScrollPaneProductDefine.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jScrollPaneProductDefine.border.titleFont"), resourceMap.getColor("jScrollPaneProductDefine.border.titleColor"))); // NOI18N
        jScrollPaneProductDefine.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneProductDefine.setName("jScrollPaneProductDefine"); // NOI18N

        jPanelProductDefine.setName("jPanelProductDefine"); // NOI18N
        jPanelProductDefine.setLayout(new java.awt.GridLayout(1, 1, 0, 2));
        jScrollPaneProductDefine.setViewportView(jPanelProductDefine);

        jTextFieldRoleSfw.setText(resourceMap.getString("jTextFieldRoleSfw.text")); // NOI18N
        jTextFieldRoleSfw.setName("jTextFieldRoleSfw"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jCheckBoxUseRole.setFont(resourceMap.getFont("jCheckBoxUseRole.font")); // NOI18N
        jCheckBoxUseRole.setForeground(resourceMap.getColor("jCheckBoxUseRole.foreground")); // NOI18N
        jCheckBoxUseRole.setSelected(true);
        jCheckBoxUseRole.setText(resourceMap.getString("jCheckBoxUseRole.text")); // NOI18N
        jCheckBoxUseRole.setName("jCheckBoxUseRole"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldUsuarioSombra.setName("jTextFieldUsuarioSombra"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextFieldSenhaSombra.setName("jTextFieldSenhaSombra"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(sfwWizardPageTitle1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1))
                        .add(4, 4, 4)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTextFieldUsuarioSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jTextFieldSenhaSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jTextFieldRoleSfw, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 344, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jCheckBoxUseRole))))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jScrollPaneProductDefine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 568, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {jLabel1, jLabel2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(sfwWizardPageTitle1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldRoleSfw, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCheckBoxUseRole))))
                .add(4, 4, 4)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextFieldUsuarioSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(jTextFieldSenhaSombra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPaneProductDefine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxUseRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelProductDefine;
    private javax.swing.JScrollPane jScrollPaneProductDefine;
    private javax.swing.JTextField jTextFieldRoleSfw;
    private javax.swing.JTextField jTextFieldSenhaSombra;
    private javax.swing.JTextField jTextFieldUsuarioSombra;
    private sfwinstaladorscript.components.SfwWizardPageTitle sfwWizardPageTitle1;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param view
     */
    public void flowSetup(SfwInstaladorScriptView view) {

        Product v_product_current;
        ProductProfileDefine v_productprofiledefine_current;
        SfwOracleDefineUser v_sfworacledefineuser_new;
        SfwOracleProductDetail v_sfworacleproductdetail_current;
        Iterator v_iterator_products, v_iterator_products_detail;
        GridLayout v_gridlayout_g = (GridLayout) this.jPanelProductDefine.getLayout();
        boolean v_boolean_product_selected;

        if (Install.get_productdefine().isEmpty()) {
            this.jPanelProductDefine.removeAll();
            this._productsdefine = new ArrayList();

            v_iterator_products = this._products.iterator();
            while (v_iterator_products.hasNext()) {
                v_product_current = (Product) v_iterator_products.next();

                v_boolean_product_selected = false;
                v_iterator_products_detail = Install.get_productsdetail().iterator();
                while (v_iterator_products_detail.hasNext()) {
                    v_sfworacleproductdetail_current = (SfwOracleProductDetail) v_iterator_products_detail.next();

                    if (v_sfworacleproductdetail_current.getProduct().get_name().equals(v_product_current.get_name())) {
                        v_boolean_product_selected = true;
                    }
                }

                if (!v_boolean_product_selected) {
                    v_sfworacledefineuser_new = new SfwOracleDefineUser(v_product_current);
                    this._productsdefine.add(v_sfworacledefineuser_new);
                    this.jPanelProductDefine.add(v_sfworacledefineuser_new);
                    v_gridlayout_g.setRows(v_gridlayout_g.getRows() + 1);

                    if (Profile.isSet()) {
                        if (Profile.get_productsdefine().containsKey(v_sfworacledefineuser_new.getProduct().get_name())) {
                            v_productprofiledefine_current = (ProductProfileDefine) Profile.get_productsdefine().get(v_sfworacledefineuser_new.getProduct().get_name());
                            v_sfworacledefineuser_new.setUser(v_productprofiledefine_current.get_user());
                            v_sfworacledefineuser_new.setPassword(v_productprofiledefine_current.get_pass());
                        }
                    }
                }
            }

            Install.set_productdefine(this._productsdefine);

            if (Profile.isSet()) {
                this.jCheckBoxUseRole.setSelected(Profile.is_userole());
                this.jTextFieldRoleSfw.setText(Profile.get_role());
                this.jTextFieldUsuarioSombra.setText(Profile.getUsuariosombra());
                this.jTextFieldSenhaSombra.setText(Profile.getSenhasombra());
            }
        } else {
            if (v_gridlayout_g.getRows() <= Install.get_productdefine().size()) {
                this.jPanelProductDefine.removeAll();
                v_gridlayout_g.setRows(1);

                v_iterator_products = Install.get_productdefine().iterator();
                while (v_iterator_products.hasNext()) {
                    this.jPanelProductDefine.add((SfwOracleDefineUser) v_iterator_products.next());
                    v_gridlayout_g.setRows(v_gridlayout_g.getRows() + 1);
                }
            }
        }
    }

    /**
     * 
     * @param wzPages
     * @param view
     */
    public void nextClick(Hashtable wzPages, SfwInstaladorScriptView view) {

        Iterator v_iterator_product_define;
        SfwOracleDefineUser v_sfworacledefineuser_current;

        v_iterator_product_define = this._productsdefine.iterator();
        while (v_iterator_product_define.hasNext()) {
            v_sfworacledefineuser_current = (SfwOracleDefineUser) v_iterator_product_define.next();

            if (!v_sfworacledefineuser_current.Validate()) {
                return;
            }
        }

        if (jTextFieldRoleSfw.getText().isEmpty()) {
            this.jTextFieldRoleSfw.requestFocus();
            JOptionPane.showMessageDialog(null, Utils.getDefaultBundle(this).getString("validationrole"), Utils.getDefaultBundle(this).getString("validationlabel"), JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Install.set_userole(this.jCheckBoxUseRole.isSelected());
            Install.set_rolesfw(this.jTextFieldRoleSfw.getText());
        }

        if (jTextFieldUsuarioSombra.getText().isEmpty()) {
            this.jTextFieldUsuarioSombra.requestFocus();
            JOptionPane.showMessageDialog(null, Utils.getDefaultBundle(this).getString("validationusersombra"), Utils.getDefaultBundle(this).getString("validationlabel"), JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Profile.setUsuariosombra(jTextFieldUsuarioSombra.getText());
        }

        if (jTextFieldSenhaSombra.getText().isEmpty()) {
            this.jTextFieldSenhaSombra.requestFocus();
            JOptionPane.showMessageDialog(null, Utils.getDefaultBundle(this).getString("validationpasssombra"), Utils.getDefaultBundle(this).getString("validationlabel"), JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Profile.setSenhasombra(jTextFieldSenhaSombra.getText());
        }

        view.setWizardPage((JPanel) wzPages.get("wzValidator"));
    }

    public void backClick(Hashtable wzPages, SfwInstaladorScriptView view) {
        this._productsdefine = new ArrayList();
        Install.set_rolesfw("");
        Install.set_userole(true);
        Install.set_productdefine(this._productsdefine);
        this.jTextFieldRoleSfw.setText("R_SFW" + Install.get_shortname());
        this.jCheckBoxUseRole.setSelected(true);
        view.setWizardPage((JPanel) wzPages.get("wzFlowDatabase"));
    }
}
